/*
 * action types for Dashboard page
*/
export const DASHBOARD_GET_ITEM_LIST = 'DASHBOARD_GET_ITEM_LIST';
export const DASHBOARD_CATEGORY_INDEX = 'DASHBOARD_CATEGORY_INDEX';
export const DASHBOARD_FILTER_INDEX = 'DASHBOARD_FILTER_INDEX';
export const DASHBOARD_SEARCH_ICON = 'DASHBOARD_SEARCH_ICON';
